//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using com.shephertz.app42.gaming.multiplayer.client.listener;
using com.shephertz.app42.gaming.multiplayer.client.command;

namespace AssemblyCSharp
{
		public class ChatListener:ChatRequestListener
		{
				string debug = "";
				public ChatListener ()
				{
				}

				public void onSendChatDone (byte result)
				{
						if (result == WarpResponseResultCode.SUCCESS) {
								Log ("onSendChatDone Success");
						} else {
								Log ("onSendChatDone Failed");
						}
				}
		
				public void onSendPrivateChatDone (byte result)
				{
						if (result == WarpResponseResultCode.SUCCESS) {
								Log ("onSendChatDone success");
						} else {
								Log ("onSendChatDone failed");
						}
				}

				private void Log (string msg)
				{
						debug = msg + "\n" + debug;
				}
		}

}

