//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using com.shephertz.app42.gaming.multiplayer.client.listener;
using com.shephertz.app42.gaming.multiplayer.client.command;

namespace AssemblyCSharp
{
	public class UpdateListener:UpdateRequestListener
		{
		string debug = "";
		      public UpdateListener ()
				{
				}

		public void onSendUpdateDone (byte result)
		{
			if (result == WarpResponseResultCode.SUCCESS)
			{
				Log("onSendUpdateDone Success ");
			}
			else
			{
				Log("onSendUpdateDone Failed ");
			}
		}
		
		public void onSendPrivateUpdateDone (byte result)
		{
			if (result == WarpResponseResultCode.SUCCESS)
			{
				Log("onSendPrivateUpdateDone Success ");
			}
			else
			{
				Log("onSendPrivateUpdateDone Failed ");
			}
		}

		private void Log(string msg)
		{
			debug = msg + "\n" + debug;
		}
   }
}

